name = "Phase4s"
uuid = "c4c67b59-b612-4a28-8b47-1c875e8dafd5"
authors = ["John Lapeyre"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Random = ">= 0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
